In [1]:
import numpy as np 

In [2]:
# in case we don't have numpy installed we can use the following code to install it
# !pip install numpy
# and if not available in pip it can be installed using conda
# !conda install numpy
# alert this might affect other projects that you are working on 

In [ ]:
# common elemnts of python
# lists, tables, sets of dictionaries
# common operations >> conditionals, loops
# numpy operations
# common pandas operations

In [7]:
# lists --> []
# specific type of object which have specific properties
# sort, append, extend with item or with another list, identify positions of items, elements, count items
# we can't remove duplicates from a list
list1 = [12, 15, 78, 15, 25]
list1.append(100)

In [8]:
list1

[12, 15, 78, 15, 25, 100]

In [10]:
# we can't append two elements
#list1.append(100, 200) # this will give an error

# but it can be done like this 
list1.append([100, 200])
list1

[12, 15, 78, 15, 25, 100, [100, 200]]

In [11]:
# to combine lists together we use extend and not append
list1.extend([100, 200, 300])
list1

[12, 15, 78, 15, 25, 100, [100, 200], 100, 200, 300]

In [12]:
# insert a value at a specific position
list1.insert(2, 1000)
list1

[12, 15, 1000, 78, 15, 25, 100, [100, 200], 100, 200, 300]

In [ ]:
# remove () or pop() to remove an element at a specific position
list1.pop(7)
list1

[12, 15, 1000, 78, 15, 25, 100, 100, 200, 300]

In [14]:
# remove() --> removes the first occurrence of a value or first time the value occurs
list1.remove(15)
list1

[12, 1000, 78, 15, 25, 100, 100, 200, 300]

In [15]:
# index() tells you the first index position of a value
list1.index(100)


5

In [17]:
# count() tells you how many times a value occurs in a list
list1.count(100)

2

In [18]:
# slicing --> isolate a range of values from a list
list1[3:7]

[15, 25, 100, 100]

In [ ]:
# slicing with step starting position: ending position : step (2 every other item)
list1[1:8:2] # every second element from index 1 to index 8

[1000, 15, 100, 200]

In [20]:
# lists support item assignment meaning we can overwrite values
list1[0] = 4000

In [21]:
list1

[4000, 1000, 78, 15, 25, 100, 100, 200, 300]

In [23]:
# tuple --> defined with round brackets (
tuple1 = (8, 7, 6, 15)

In [24]:
# count the number of elements of a certain value
tuple1.count(8)

1

In [25]:
# find the first position of a certain value
tuple1.index(15)

3

In [26]:
# find a value in a certain position
tuple1[0]

8

In [27]:
# you cannot overwrite or change values in a tuple
tuple1[0] = 1000 # this will give an error

TypeError: 'tuple' object does not support item assignment

In [28]:
# sets --> defined with curly brackets {}
set1 = {12, 13, 15, 18, 25, 15, 100, 100}

In [29]:
# sets do not hold duplicates, so even if you define one with dupes it will remove them
set1

{12, 13, 15, 18, 25, 100}

In [30]:
# create set2
set2 = {13, 100, 18, 14, 27, 35}

In [31]:
# find common elements between two sets
set1.intersection(set2)

{13, 18, 100}

In [32]:
# find elements that exist in set 1 but NOT in set 2
set1.difference(set2)

{12, 15, 25}

In [33]:
# find elements in set 2 but NOT in set 1
set2.difference(set1)

{14, 27, 35}

In [34]:
# if i only want to keep the elements in set2 that are different from set1
set2.difference_update(set1)

In [35]:
set2

{14, 27, 35}

In [36]:
# pthon built in functions set 
# https://docs.python.org/3/library/functions.html


In [37]:
# find common elements between set1 and list1
set1.intersection(list1)

{15, 25, 100}

In [39]:
# global fiunction like sum() 
sum(list1)

5818

In [40]:
sum(set1)

183

In [41]:
sum(tuple1)

36

In [42]:
min(list1)

15

In [43]:
max(set2)

35

In [44]:
# dictionaries
dict1 = {'ON': 'Toronto', 'MB': 'Winnipeg', 'SK': 'Regina', 'BC': 'Victoria'}

In [45]:
# functions work on dictionaries
# all the keys of the dictionary
dict1.keys()

dict_keys(['ON', 'MB', 'SK', 'BC'])

In [46]:
# isolate the values of the dictionary
dict1.values()

dict_values(['Toronto', 'Winnipeg', 'Regina', 'Victoria'])

In [51]:
# hierarchical data example - shopping cart
dict2 = {'customer1': {'books': ['book1', 'book2'], 'food': ['chips', 'tomatos']}, 'customer2': {'clothing': [ 'socks', 'skirt'], 'electronic': [ 'tv', 'computer', 'ipad']}}

In [52]:
# show the keys of the main dictionary
dict2.keys()

dict_keys(['customer1', 'customer2'])

In [53]:
# show the values of the main dictionary
dict2.values()

dict_values([{'books': ['book1', 'book2'], 'food': ['chips', 'tomatos']}, {'clothing': ['socks', 'skirt'], 'electronic': ['tv', 'computer', 'ipad']}])

In [55]:
# show the keys of customer1
dict2['customer1'].keys()

dict_keys(['books', 'food'])

In [56]:
# show the values of customer1
dict2['customer1'].values()

dict_values([['book1', 'book2'], ['chips', 'tomatos']])

In [57]:
# adding a new key:value to a dictionary - just add one that doesn't exist
dict2['customer3'] = {'groceries':['chips','pop'], 'shoes':['running shoes', 'tennis shoes']}

In [58]:
dict2

{'customer1': {'books': ['book1', 'book2'], 'food': ['chips', 'tomatos']},
 'customer2': {'clothing': ['socks', 'skirt'],
  'electronic': ['tv', 'computer', 'ipad']},
 'customer3': {'groceries': ['chips', 'pop'],
  'shoes': ['running shoes', 'tennis shoes']}}

In [59]:
# removing an element, we can use pop()
dict2.pop('customer3')

{'groceries': ['chips', 'pop'], 'shoes': ['running shoes', 'tennis shoes']}

In [60]:
dict2

{'customer1': {'books': ['book1', 'book2'], 'food': ['chips', 'tomatos']},
 'customer2': {'clothing': ['socks', 'skirt'],
  'electronic': ['tv', 'computer', 'ipad']}}

In [ ]:
# show the items of the main dictionary
dict2.items()

dict_items([('customer1', {'books': ['book1', 'book2'], 'food': ['chips', 'tomatos']}), ('customer2', {'clothing': ['socks', 'skirt'], 'electronic': ['tv', 'computer', 'ipad']})])

In [64]:
# conditionals statements
x = 9*12/14+100

In [65]:
if x > 10: 
    print(f'{x} is greater than 10')
else: 
    print(f'{x} is not greater than 10')

107.71428571428571 is greater than 10


In [66]:
y = 9*12/14+100

In [68]:
if y > 10: 
    y = (y+15) / 22
else: 
    y = 0

print(y)

0


In [ ]:
if y > 10: 
    y = (y+15) / 22
    y = y/12
    print(f'{y} is calculated')

else: 
    y = 0

print(y)

0


In [72]:
# conditional statements
x = 9*12/14+10

In [73]:
# make sure conditions are mutually exclusive
if x > 10:
  x = (x + 15) / 22
  x = x/12
  print(f'{x} is calculated')
elif x > 5 and x <= 10:
  x = (x +10) / 12
  print(x)

else:
  x = 0

0.12391774891774893 is calculated


In [75]:
# looping -- the for loop 

for i in list1:
    if i > 10:
        i = (i + 15) / 22
        i = i / 12
        print(f'{i} is calculated')
    elif i > 5 and i <= 10:
        i = (i + 10) / 12
        print(i)
    else:
        i = 0

15.208333333333334 is calculated
3.8446969696969693 is calculated
0.3522727272727273 is calculated
0.11363636363636363 is calculated
0.15151515151515152 is calculated
0.4356060606060606 is calculated
0.4356060606060606 is calculated
0.8143939393939394 is calculated
1.1931818181818181 is calculated


In [ ]:
# it will print the items of the dictionary as a tuple (key, value)
for i in dict2.items():
    print(i)

('customer1', {'books': ['book1', 'book2'], 'food': ['chips', 'tomatos']})
('customer2', {'clothing': ['socks', 'skirt'], 'electronic': ['tv', 'computer', 'ipad']})


In [77]:
# calculate how many items from each major category were ordered
categories_w_purchases = []
items_purchased = []
num_categories = 0
num_items = 0
num_items_by_category = {}

for key, value in dict2.items():
  for a, b in value.items():
    if a not in categories_w_purchases:
      categories_w_purchases.append(a)
      num_categories += 1
    for item in b:
      if item not in items_purchased:
        items_purchased.append(item)
        num_items += 1
      if a not in num_items_by_category.keys():
        num_items_by_category[a] = 1
      else:
        num_items_by_category[a] += 1

print(categories_w_purchases)
print(items_purchased)
print(num_categories)
print(num_items)
print(num_items_by_category)

['books', 'food', 'clothing', 'electronic']
['book1', 'book2', 'chips', 'tomatos', 'socks', 'skirt', 'tv', 'computer', 'ipad']
4
9
{'books': 2, 'food': 2, 'clothing': 2, 'electronic': 3}


In [78]:
# import numpy 
import numpy as np

In [91]:
arr1 = np.array(list1)

In [92]:
arr1

array([4000, 1000,   78,   15,   25,  100,  100,  200,  300])

In [93]:
arr1.mean()

np.float64(646.4444444444445)

In [94]:
arr1.sum()

np.int64(5818)

In [95]:
arr1.astype(float)

array([4000., 1000.,   78.,   15.,   25.,  100.,  100.,  200.,  300.])

In [96]:
arr1[0]

np.int64(4000)

In [97]:
arr1.shape

(9,)

In [98]:
arr1 = np.append(arr1, 500)

In [99]:
arr1.shape

(10,)

In [100]:
arr1.reshape(5,2)

array([[4000, 1000],
       [  78,   15],
       [  25,  100],
       [ 100,  200],
       [ 300,  500]])

In [101]:
arr1.reshape(2,5)

array([[4000, 1000,   78,   15,   25],
       [ 100,  100,  200,  300,  500]])

In [102]:
# projection of arreys
arr2 = np.array([10])

In [103]:
arr1 + arr2

array([4010, 1010,   88,   25,   35,  110,  110,  210,  310,  510])

In [104]:
arr1 * arr2

array([40000, 10000,   780,   150,   250,  1000,  1000,  2000,  3000,
        5000])